### ISSUE TITLE
Put rest of project in repo, not on gdrive(?!)

### ISSUE THREAD

**Issue by OranguTech** [Napalm1473/Battletech-2018-Interactive-Map#1]
Cool project idea.

I too am learning "the skills" when it comes to the web/programming side, went to look at the project and...almost everything is on gdrive?!?

Is there a reason the rest of the files are on gdrive, not in the repo? I have experience on the project/git(hub) side of things, if you're just starting out...

**Comment by OranguTech** [comment]
Ah, the whole gdrive folder includes the full download the leaflet.js plugins, scripts/leaflet-search-master/examples/ for example, which includes a 3 meg text file. Definitely will need some cleanup, but I'm happy to help if you need it.

**Comment by OranguTech** [comment]
No reply, no comment, no action?

**Comment by Napalm1473** [comment]
Im away at work in the mines for a few weeks. Have added you as a collaborator.

**Comment by OranguTech** [comment]
If you trust a random stranger on the inet, yes you can add me as a
collaborator. (
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/),
which would give me a fair bit  of permissions to the repo. (
https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account)
Nothing
that can't be reversed I think. (I assume you don't have it set to
auto-publish to the website version or anything.)

Alternately, just wait until you have some time and I have more useful
changes.

Thanks for making this!
